# Generated by Django 4.0.4 on 2022-10-09 17:14

import cloudinary.models
from django.db import migrations
import petstagram.common.project_validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[petstagram.common.project_validators.ImageMaxSizeValidatorInMb(5)], verbose_name='image'),
        ),
    ]
